"""empty message

Revision ID: 33052bc4a1d8
Revises: bbc9759b2d76
Create Date: 2024-09-28 15:29:51.932111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33052bc4a1d8'
down_revision: Union[str, None] = 'bbc9759b2d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('location', sa.String(), nullable=False),
                    sa.Column('services', sa.ARRAY(
                        sa.String(40)), nullable=True),
                    sa.Column('rooms_quantity', sa.Integer(), nullable=False),
                    sa.Column('image_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('hotels', 'services',
                    existing_type=postgresql.ARRAY(sa.Integer()),
                    type_=postgresql.JSON(astext_type=sa.Text()),
                    existing_nullable=True)
    # ### end Alembic commands ###
