"""empty message

Revision ID: be2b66651ac5
Revises: 33052bc4a1d8
Create Date: 2024-10-03 13:24:40.424874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2b66651ac5'
down_revision: Union[str, None] = '33052bc4a1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('hotels', 'image_id')
    op.create_foreign_key(None, 'rooms', 'hotels', ['hotel_id'], ['id'])
    op.drop_column('rooms', 'image_id')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('rooms', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.add_column('hotels', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('rooms_images')
    op.drop_table('hotels_images')
    # ### end Alembic commands ###
